version: '3.8'
services:
  vue-app:
    build: .
    ports:
      - "${STACK_PORT}:8000"
    environment:
      - NODE_ENV=production
    networks:
      - vue-network

# Define the network to be used by this stack
networks:
  vue-network:
    driver: bridge