// Interface automatically generated by schemas-to-ts


import type {Media} from "@/scripts/interfaces/defaults/Media";

export interface Motion {
  motionTitle: string;
  motionContext?: string;
  motionPiece: { data: Media };
  motionCover: { data: Media };
}
export interface Motion_Plain {
  motionTitle: string;
  motionContext?: string;
  motionPiece: Media;
  motionCover: Media;
}

export interface Motion_NoRelations {
  motionTitle: string;
  motionContext?: string;
  motionPiece: number;
  motionCover: number;
}

