// Interface automatically generated by schemas-to-ts


import type {Media} from "@/scripts/interfaces/defaults/Media";

export interface Track {
  trackTitle: string;
  trackContext?: string;
  trackPiece: { data: Media };
  trackCover: { data: Media };
}
export interface Track_Plain {
  trackTitle: string;
  trackContext?: string;
  trackPiece: Media;
  trackCover: Media;
}

export interface Track_NoRelations {
  trackTitle: string;
  trackContext?: string;
  trackPiece: number;
  trackCover: number;
}

